/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static proyectofinal.JParser.Objetos;

/**
 *
 * @author jonat
 */
public class JInicio extends javax.swing.JFrame {

    JParser llamar =  new JParser();
    String Concatenar = "";
    
    
    public JInicio() {
         initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }
    
    public JInicio(int x,int y){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Areaconsola = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Areaobjetos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Jbanalizar = new javax.swing.JButton();
        Jbabrir = new javax.swing.JButton();
        Jbguardar = new javax.swing.JButton();
        Jbacerca = new javax.swing.JButton();
        Jbsalir = new javax.swing.JButton();
        Jbtablero = new javax.swing.JButton();
        Jbreporte = new javax.swing.JButton();
        Jbreporte2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setText("Consola");

        Areaconsola.setColumns(20);
        Areaconsola.setRows(5);
        jScrollPane1.setViewportView(Areaconsola);

        Areaobjetos.setColumns(20);
        Areaobjetos.setRows(5);
        Areaobjetos.setEnabled(false);
        jScrollPane2.setViewportView(Areaobjetos);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setText("Objetos");

        Jbanalizar.setText("Analizar");
        Jbanalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbanalizarActionPerformed(evt);
            }
        });

        Jbabrir.setText("Abrir");
        Jbabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbabrirActionPerformed(evt);
            }
        });

        Jbguardar.setText("Guardar");
        Jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbguardarActionPerformed(evt);
            }
        });

        Jbacerca.setText("Acerca de");
        Jbacerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbacercaActionPerformed(evt);
            }
        });

        Jbsalir.setText("Salir");
        Jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalirActionPerformed(evt);
            }
        });

        Jbtablero.setText("Tablero");
        Jbtablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtableroActionPerformed(evt);
            }
        });

        Jbreporte.setText("Reporte Tokens");
        Jbreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbreporteActionPerformed(evt);
            }
        });

        Jbreporte2.setText("Reporte Errores");
        Jbreporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbreporte2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jbtablero)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(Jbanalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jbabrir)
                                .addGap(18, 18, 18)
                                .addComponent(Jbguardar)
                                .addGap(18, 18, 18)
                                .addComponent(Jbacerca)
                                .addGap(18, 18, 18)
                                .addComponent(Jbsalir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jbreporte2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jbreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Jbanalizar)
                    .addComponent(Jbabrir)
                    .addComponent(Jbguardar)
                    .addComponent(Jbacerca)
                    .addComponent(Jbsalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbreporte)
                    .addComponent(Jbreporte2)
                    .addComponent(Jbtablero))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalirActionPerformed
       int option = JOptionPane.showConfirmDialog(null, "Desea Cerrar la aplicacion?","Cerrar Aplicacion",JOptionPane.YES_NO_OPTION);
        if(JOptionPane.OK_OPTION == option){
            System.exit(0);
        }else {
            
        }
    }//GEN-LAST:event_JbsalirActionPerformed

    private void JbacercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbacercaActionPerformed
       JOptionPane.showMessageDialog(null,"Jonatan Alejandro Azurdia Aju \n" + "201512786 \n" + "LFP");
    }//GEN-LAST:event_JbacercaActionPerformed

    private void JbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbguardarActionPerformed
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileOutputStream salida;
        
        if(seleccionar.showDialog(this, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Docuemnto= Areaconsola.getText();
                String mensaje = Guardar(archivo, Docuemnto);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no Compatible");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Guardar Documento de Texto");
            }
        }
    }//GEN-LAST:event_JbguardarActionPerformed

    private void JbabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbabrirActionPerformed
      JFileChooser selector = new JFileChooser();
            selector.showOpenDialog(selector);
            String nuevo = "";
            
            try{
               String direccion = selector.getSelectedFile().getAbsolutePath();
               FileInputStream archivo = new FileInputStream(direccion);
                DataInputStream entrada = new DataInputStream(archivo);
                
                BufferedReader lector = new BufferedReader(new InputStreamReader(entrada));
                String lineas;
                
                while((lineas = lector.readLine()) != null){
                  nuevo += lineas + "\n";
                  Areaconsola.setText(nuevo);
                }
                
                entrada.close();
                
            }catch(Exception ios){
                JOptionPane.showMessageDialog(null, "No se cargo ningun archivo");
            }
    }//GEN-LAST:event_JbabrirActionPerformed

    private void JbanalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbanalizarActionPerformed
        JAnalizador scanner = new JAnalizador(Areaconsola.getText());        
        scanner.Analizador();        

        ArrayList<JTemporal> lista = scanner.Lista_Temporal;
//        String resultado = "";
//        for(int i=0;i<lista.size();i++){
//            resultado+= "Token: " + lista.get(i).getToken() + " " + lista.get(i).getLexema()+ "\n";
//        }
//        
//        Areaobjetos.setText(resultado);
        
        int cantidad = lista.size();
       JParser parser = new JParser();
       parser.Parsear(lista,cantidad);
       //parser.Mostrar_Datos(); //si quito esto ya no lo muestra
       System.out.println("------------------"); //separador
       parser.Contenedor();
       Areaobjetos.setText(parser.concatenar);
       parser.Mostrar_Objetos();
    }//GEN-LAST:event_JbanalizarActionPerformed

    private void JbreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbreporteActionPerformed
       JAnalizador reporte = new JAnalizador(Areaconsola.getText());
       reporte.GenerarReporteTokens();
       
                        try {
                        File path = new File ("C:\\Users\\jonat\\Documents\\NetBeansProjects\\ProyectoFinal\\Reportedetokens.html");
                        Desktop.getDesktop().open(path);
                        }catch (IOException ex) {
                        ex.printStackTrace();
                        }
       
    }//GEN-LAST:event_JbreporteActionPerformed

    private void Jbreporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbreporte2ActionPerformed
         JAnalizador reporte = new JAnalizador(Areaconsola.getText());
         reporte.ReporErrores();
       
                        try {
                        File path = new File ("C:\\Users\\jonat\\Documents\\NetBeansProjects\\ProyectoFinal\\Reportedeerrores.html");
                        Desktop.getDesktop().open(path);
                        }catch (IOException ex) {
                        ex.printStackTrace();
                        }
       
    }//GEN-LAST:event_Jbreporte2ActionPerformed

    private void JbtableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtableroActionPerformed
        JJuego jugar = new JJuego();
        try{
        jugar.setVisible(true);
        }catch(Exception ios){
            JOptionPane.showMessageDialog(null, ios);
        }
    }//GEN-LAST:event_JbtableroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Areaconsola;
    private javax.swing.JTextArea Areaobjetos;
    private javax.swing.JButton Jbabrir;
    private javax.swing.JButton Jbacerca;
    private javax.swing.JButton Jbanalizar;
    private javax.swing.JButton Jbguardar;
    private javax.swing.JButton Jbreporte;
    private javax.swing.JButton Jbreporte2;
    private javax.swing.JButton Jbsalir;
    private javax.swing.JButton Jbtablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    //Guardar metodo
    public String Guardar(File archivo, String documento){
        FileOutputStream salida;
        String mensaje=null;
        try{
            salida= new FileOutputStream(archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo guardado";
        }catch(IOException e){ 
            System.out.println("Error: "+e.getMessage());
        }
        
        return mensaje;
    }
    //Fin del metodo

             

}
